
-- 숙제 다시 풀어보기

-- 1번

SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT;

-- 2번


SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || ' 명 입니다.' "학과별 정원" 
FROM TB_DEPARTMENT;


-- 3번


SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN ='Y' AND STUDENT_SSN LIKE '_______2%';

-- 4번

SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119') 
ORDER BY STUDENT_NAME DESC;


-- 5번

SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;


-- 6번

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7번

SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO  IS NULL;

-- 8번

SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


-- 9번

SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

-- 10번

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' 
AND ENTRANCE_DATE BETWEEN '2002-01-01' AND '2002-12-31'
AND STUDENT_ADDRESS LIKE '%전주%'
ORDER BY STUDENT_NAME;


SELECT ABS(ROUND(MONTHS_BETWEEN(SYSDATE, '2023-12-31'),1)) ||'개월 남았습니다.' "2023년도 남은 개월 수"
FROM DUAL;


SELECT EMP_NAME , HIRE_DATE ,
CEIL (MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) || '일 수 근무했습니다.' "근무 일 수"  
FROM EMPLOYEE;

-- 학생 테이블에서 전주 빼고 전주 뒤로만 출력하기


SELECT SUBSTR(STUDENT_ADDRESS, INSTR(STUDENT_ADDRESS, '전주') +2) || ' ㅎㅎ 풀었다' "풀었따"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%';


